version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"  
      - "9090:9090"
    environment:
      - SERVER_ADDRESS=0.0.0.0:8080
      - TCP_PORT=:9090

