openapi: 3.0.0
info:
  title: Micro Payment Gateway API
  description: API for processing payments via multiple gateways.
  version: 1.0.0

servers:
  - url: http://localhost:8080
    description: Local server

paths:
  /deposit:
    post:
      summary: Process a deposit transaction
      requestBody:
        description: Deposit details
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PaymentRequest"
      responses:
        "202":
          description: Deposit accepted
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PaymentResponse"
        "400":
          description: Invalid request
        "500":
          description: Server error

  /withdraw:
    post:
      summary: Process a withdrawal transaction
      requestBody:
        description: Withdrawal details
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PaymentRequest"
      responses:
        "202":
          description: Withdrawal accepted
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PaymentResponse"
        "400":
          description: Invalid request
        "500":
          description: Server error

  /callback:
    post:
      summary: Handle callback from payment gateway
      requestBody:
        description: Callback details
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CallbackRequest"
      responses:
        "200":
          description: Callback handled successfully
        "400":
          description: Invalid request
        "500":
          description: Server error

components:
  schemas:
    PaymentRequest:
      type: object
      properties:
        userId:
          type: string
          description: ID of the user making the transaction
        currency:
          type: string
          description: Currency of the transaction
        amount:
          type: integer
          description: Amount to be deposited/withdrawn
        countryCode:
          type: string
          description: Country code of the transaction
      required:
        - userId
        - currency
        - amount
        - countryCode

    PaymentResponse:
      type: object
      properties:
        status:
          type: string
          description: Status of the transaction
        message:
          type: string
          description: Message related to the transaction status
        id:
          type: string
          description: ID of the transaction

    CallbackRequest:
      type: object
      properties:
        transaction_id:
          type: string
          description: ID of the transaction
        state:
          type: string
          description: State of the transaction (approved/failed)
